version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    ports:
      - "27017:27017" 

  api:
    build: 
      context: ..
      dockerfile: devops/SERVER/Dockerfile
    ports:
      - "5000:5000" 

  app:
    build: 
      context: ..
      dockerfile: devops/APP/Dockerfile
    ports:
      - "80:3000" 

