version: '3.1'

services:

  api:
    build: 
      context: ..
      dockerfile: devops/SERVER/Dockerfile
    ports:
      - "5000:5000" 

  app:
    build: 
      context: ..
      dockerfile: devops/APP/Dockerfile
    ports:
      - "80:3000" 

